### ISSUE TITLE
Preset list of the Spiral coaster works incorrectly (if I have Korean-named custom track)

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#10541]
**OS:** Windows 10
**Version:** 0.2.4
**Commit/Build:** 8893d99

I'm not sure if it is the certain problem with the spiral coaster, anyway, I think its preset list works incorrectly if I have custom track which of its name contains non-english, such as korean.

**Steps to reproduce:**
1. Name any custom track file(*.TD6) containing non-english characters, such as ``테스트.TD6``
2. Store it in _(Doc)/OpenRCT2/track_ directory
3. Run the game, try to build a spiral coaster
4. See the preset coaster list

**Screenshots / Video:**
![image](https://user-images.githubusercontent.com/10726524/72205520-5b1d3b00-34c7-11ea-91be-972e500de073.png)
(Note that ``원심분리기.TD6`` is not a custom design of Spiral coaster, but it looks it is shown as an empty entry)

If I try to click the ``""`` entry:
![image](https://user-images.githubusercontent.com/10726524/72205573-0a5a1200-34c8-11ea-92ed-1925d1a4c187.png)

In English, if I try to click _Build custom design_ first without any clicking other entries, it works.
If I try to click the corrupted entry, it shows error message. Then if I click _Build custom design_ again, it shows the same error.
In Korean, whatever I try to click first, it shows the error.

**Comment by Gymnasiast** [comment]
The reason it does this is because the Spiral Roller Coaster has ride type index 0.

This works for me on Linux, so it appears to be Windows-specific.

**Comment by AaronVanGeffen** [comment]
Is this also resolved by #10540?

**Comment by Gymnasiast** [comment]
#10540 has been merged in the meantime. @telk5093 , could you try the develop version 09ac8a0c59b4bc35c8758aae6ee00e5e4ecbc4f2 or newer?

**Comment by telk5093** [comment]
@Gymnasiast Thanks for notice, unfortunately it doesn't solve this issue.

**Comment by telk5093** [comment]
@Gymnasiast I've checked recent develop(2340206), and it seems that there is no problem anymore :)
