### ISSUE TITLE
Strange window and mouse behaviours under Wayland session

### ISSUE THREAD

**Issue by rmnvgr** [OpenRCT2/OpenRCT2#12718]
**OS:** Fedora 32
**Version:** 0.3.0 (Flatpak)
**Commit/Build:** 135cc10

The recently released Flatpak build of OpenRCT2 [uses Wayland to show the game window](https://github.com/flathub/flathub/pull/1694#issuecomment-674514781) under a Wayland session. That introduces several strange behaviours:
- The window has no decorations
- The cursor is bigger
- The pointer cursor is a full hand
- When right-clicking and dragging to move the view, instead of the view following the mouse movement, the panning accelerates as you move away from the origin. After a few pixels it becomes uncontrollable.

**Steps to reproduce:**
1. Install the [Flatpak version of OpenRCT2](https://flathub.org/apps/details/io.openrct2.OpenRCT2)
2. Launch it under a Wayland session

**Screenshots / Video:**

Wayland | X11
--------|----
![Window under Wayland](https://user-images.githubusercontent.com/66537460/90482647-d157df00-e133-11ea-9f87-85887160328a.png)<br>No window decorations | ![Window under X11](https://user-images.githubusercontent.com/66537460/90482791-0cf2a900-e134-11ea-96af-30495e2fd2a1.png)<br>Window decorations
![Cursor under Wayland](https://user-images.githubusercontent.com/66537460/90483098-8094b600-e134-11ea-8c0c-a301b6edfd28.png)<br>Cursor is bigger than in other applications | ![Cursor under X11](https://user-images.githubusercontent.com/66537460/90483118-88545a80-e134-11ea-8419-89138e7f8d69.png)<br>Cursor is the regular size
![Cursor under Wayland](https://user-images.githubusercontent.com/66537460/90483309-d36e6d80-e134-11ea-91c3-95dd7e9de22f.png)<br>Pointer cursor is a hand | ![Cursor under X11](https://user-images.githubusercontent.com/66537460/90483336-d9fce500-e134-11ea-9d0b-bf39fd81dfe3.png)<br>Pointer cursor is the pointer cursor

cc @takluyver

**Comment by takluyver** [comment]
There should be some way to get it to use Wayland with a normal build - maybe unsetting the `DISPLAY` environment variable? This would a) check if the issue is Wayland in general or Wayland plus sandboxing, and b) offer a way to test changes without having to recreate a Flatpak each time.

**Comment by IntelOrca** [comment]
Out of curiosity, do you get any of these issues with other games that use SDL2?

**Comment by takluyver** [comment]
... could the fact that I used SDL 1.2 in the Flatpak recipe be related? :astonished: :wink:

**Comment by AaronVanGeffen** [comment]
I'm surprised you could even get it to compile with SDL 1.2 …?

**Comment by takluyver** [comment]
Ah, no, the base image contains SDL 2.0.12. So I was just needlessly building SDL 1.2.

**Comment by rmnvgr** [comment]
> Out of curiosity, do you get any of these issues with other games that use SDL2?

I tried with [OpenTTD](https://github.com/OpenTTD/OpenTTD/) and [Julius](https://github.com/bvschaik/julius/), both of which should use SDL2:
- In OpenTTD, the window has decorations, the right-click dragging works, and they use sprites for the cursor
- In Julius, the window doesn't have decorations under Wayland but do under X11, the right-click dragging works, and they use sprites for the cursor

**Comment by IntelOrca** [comment]
I think OpenTTD still uses SDL1 so that probably isn't a good comparison.

**Comment by rmnvgr** [comment]
> I think OpenTTD still uses SDL1 so that probably isn't a good comparison.

They list SDL2 in their [requirements](https://github.com/OpenTTD/OpenTTD/blob/master/COMPILING.md), but to have more comparisons I also tried the flatpak versions of 0A.D. and Battle for Wesnoth:
- In 0A.D., the windows has decorations, the middle-click dragging works, and they use sprites for the cursor
- In Battle for Wesnoth, the window doesn't have decorations under Wayland but do under X11, the middle-click dragging has the same behaviour under Wayland and X11, and they use sprites for the cursor

Something else I noticed is that under Wayland, windows are very small, whereas under X11 they take the whole screen.

**Comment by rmnvgr** [comment]
I did some digging around and found some interesting things:

- SDL2 under Wayland doesn't provide client-side decorations, so if the WM doesn't implement server-side decorations, no window decorations will be shown. I don't know for other desktops but [for GNOME and Mutter that's not the case](https://gitlab.gnome.org/GNOME/mutter/-/issues/217). 
- SDL2 under Wayland [doesn't support mouse warping](https://github.com/spurious/SDL-mirror/blob/3384f7b2845eeeae887386d0879a24d066678775/src/video/wayland/SDL_waylandmouse.c#L351). OpenRCT2's [`input_viewport_drag_continue`](https://github.com/OpenRCT2/OpenRCT2/blob/853f718aeeea0c81649f803f2c9a493236fca157/src/openrct2-ui/input/MouseInput.cpp#L521) relies on it to prevent the cursor from moving. Because the cursor keeps moving under Wayland, the differential coords get high very fast, so dragging the viewport moves the view exponentially faster.

I don't know if SDL2 plans to support client-side decorations, but having no window decorations is not a problem in itself as OpenRCT2 offers ways to close the window via the UI or keyboard shortcuts. However, it is impossible to resize the window.

As for the viewport dragging, I'm not sure if it's a limitation of Wayland or SDL2. In any case, unless `SDL_WarpMouseInWindow` gets supported under Wayland, it would require rewriting the drag logic of OpenRCT2.

I did not look for the cursor sizing and styling issues.

@takluyver, I know [you wanted ](https://github.com/flathub/flathub/pull/1694#issuecomment-674514781)to keep using Wayland by default for the Flatpak to keep the bugs visible, but considering they are implementation problems with SDL2 and have in my opinion little chance of being fixed soon, I would suggest using the X11 backend instead. The bugs are identified and I don't really like giving users a purposely broken experience.

**Comment by takluyver** [comment]
Fair enough. It's disappointing that the pieces don't all fit together yet, but I agree that it doesn't make sense to expose the problems to users if it works better with X11. My idea to keep the bugs visible was in the hope that they were application bugs and could be fixed reasonably quickly, but it sounds like that's not the case.

It does look like SDL is open to implementing client-side decorations, but it's still some way off (unless my quick search of issues missed something):

- https://bugzilla.libsdl.org/show_bug.cgi?id=4845
- https://bugzilla.libsdl.org/show_bug.cgi?id=5194

**Comment by puyoxyz** [comment]
> I don't know if SDL2 plans to support client-side decorations

SDL2(0.1.6) now supports CSD through [libdecor](https://gitlab.gnome.org/jadahl/libdecor), including it in the Flatpak should fix the no-window-decorations issue?

**Comment by rmnvgr** [comment]
Yes, using libdecor fixes missing window decorations.

However, these issues remain:

>- The pointer cursor is a full hand
>- When right-clicking and dragging to move the view, instead of the view following the mouse movement, the panning accelerates as you move away from the origin. After a few pixels it becomes uncontrollable.

**Comment by rmnvgr** [comment]
I recently tried again running OpenRCT2 with Wayland (using `flatpak run --nosocket=x11 --socket=wayland io.openrct2.OpenRCT2`) and almost everything works.

The last remaining issue is that when right-clicking and dragging the view, even though it now pans the view as expected (without accelerating), when you stop moving the mouse, the view keeps slowly panning in the last direction until you release the right click.

**Comment by rmnvgr** [comment]
The last issue has been resolved, OpenRCT2 now works perfectly under Wayland.

I have switched the Flatpak to use Wayland by default (it will still use X11 for those under an Xorg session).

**Comment by janisozaur** [comment]
Huh, I somehow completely missed this issue report, even though there was some discussion. I saw updates to OpenRCT2 runtime version, is that all that has to be done? Anything that we need/needed to do? I should test native (non-flatpak) version with Wayland as well, but honestly I don't even know if any of my systems use it.

**Comment by rmnvgr** [comment]
I don't think anything has/had to be done on OpenRCT2's side, updating the runtime gave access to a newer version of SDL2 that fixed the issue.
