### ISSUE TITLE
Non-ASCII thousands and decimal separators not processed correctly

### ISSUE THREAD

**Issue by groenroos** [OpenRCT2/OpenRCT2#14630]
In some languages (such as Finnish), thousands are usually separated by spaces. However, this means that in some cases the number can confusingly wrap onto multiple lines, as the space makes the parts of the single number behave like two separate words;

<img width="263" alt="Screenshot 2021-05-11 at 18 04 13" src="https://user-images.githubusercontent.com/951547/117856432-82cf0f80-b283-11eb-872c-cd1589ca18e6.png">

Numbers being injected into strings should be protected from being wrapped onto multiple lines.

**Comment by ZxBiohazardZx** [comment]
would it be an idea to use the UNICODE non-breaking space ( U+00A0) as opposite of the normal space (U+0020)

not sure you can add that as character in the localisation in an easy way (U00A0 as seperator)

**Comment by ShimmerFairy** [comment]
If Unicode is an option, then using NBSP as mentioned would be an easy way to specify spaces that should not be broken across lines. In fact, for reference, [Unicode comes with a line breaking algorithm, specified in UAX#14](https://www.unicode.org/reports/tr14/). So even if you had to write your own Unicode-aware line breaker (as opposed to using some library that figures it out for you), you at least wouldn't have to figure out an algorithm by yourself.

**Comment by groenroos** [comment]
If the Unicode (or some other) non-breaking space character is supported, then it's a gotcha for translators, but at least the user-facing issue can be resolved. Are non-breaking spaces supported & respected in the game currently?

**Comment by Gymnasiast** [comment]
Yes, they are. I fixed that to allow for French-style punctuation (which similarly puts a non-breaking space before `!` and `?`).

**Comment by groenroos** [comment]
I just tried giving it a go with a single `U+00A0` for `STR_5151`, but the same behaviour still happens - the two segments of the number are still split onto two lines... 😕 

I'm running `0.3.3 (3f65f282d)` if that makes a difference.

**Comment by groenroos** [comment]
I noticed that my previous attempt was thwarted by my IDE trying to be "helpful" by converting my non-breaking spaces to regular spaces.

I now added a proper `U+00A0` for `STR_5151` in OpenRCT2/Localisation#2832 - however, I had to close that PR, because in-game this seems to corrupt any parent string that needs a thousands separator, by truncating the rest of the string:

<img width="341" alt="Screenshot 2024-05-19 at 19 42 34" src="https://github.com/OpenRCT2/OpenRCT2/assets/951547/f09803ba-d23a-4590-9122-000867ba0806">

I'm assuming the same character works fine for punctuation in `fr-FR` (albeit it looks like they also use a regular space for `STR_5151`?). Is there something extra that needs to be fixed or enabled to make non-breaking spaces work for `fi-FI` in this context?

**Comment by Gymnasiast** [comment]
If I had to hazard a guess: the symbol is represented by two bytes in UTF-8, and our code probably makes an assumption somewhere that the symbol is ASCII.

**Comment by Gymnasiast** [comment]
@groenroos A fix is pending, are you able to check that out?

**Comment by groenroos** [comment]
@Gymnasiast Thanks - built it locally, and that does indeed seem to fix the issue! 🎉 

As for OpenRCT2/Localisation#2832, given that we probably wouldn't want to distribute those strings unless your patch was also merged, would it be safe to re-open that PR now, or wait for later?
