### ISSUE TITLE
Improper Opaque Water Behavior

### ISSUE THREAD

**Issue by ZeeMaji** [OpenRCT2/OpenRCT2#14753]
The new RCT1 style opaque water should temporarily change to transparent when using construction tools (land tool, water tool, scenery clear tool, ride construction, path tool, etc...) as it behaves like this in RCT1.
The scenery tool seems to be excluded from this in RCT1 and it instead displays a square grid on the surface of water you hover over with your cursor like the water tool does.
![DeepinScreenshot_explorer exe_20210526111048](https://user-images.githubusercontent.com/42477864/119685883-c4c78c00-be13-11eb-9058-434485a66afd.png)

**Comment by Gymnasiast** [comment]
Wouldn't it be easier if we just drew the box on the water as well? To me, it seems that would ease placement anyway, regardless of whether the water is transparent.

**Comment by ZeeMajora** [comment]
That'd also work, yeah.

**Comment by IntelOrca** [comment]
@Gymnasiast when/if you work on this, you should also call `gfx_invalidate_screen()` when you flip the transparent water flag to make sure the whole screen is redrawn in software mode. I think @telk5093 raised this issue in the discord chat.

**Comment by AaronVanGeffen** [comment]
I believe this was addressed by #21266.

**Comment by ZeeMaji** [comment]
It was not, the grid is still not displayed on the water's surface when placing scenery items.

**Comment by Gymnasiast** [comment]
@sjoerddebruin Something for you? In this case, the placement should stay the same (unlike the staff assignment area), it just needs to draw a secondary box drawn on the water for at least small scenery, walls and paths.
