### ISSUE TITLE
Exit path disconnect in sandbox mode

### ISSUE THREAD

**Issue by Phasedetect** [OpenRCT2/OpenRCT2#1502]
I used sandbox mode to change a tarmac path to a light brown footpath. This change disconnected the path from the map edge, preventing peeps from leaving. It doesn't affect the park rating, because all of the disgruntled guests are outside the park boundaries, and guests can still enter the park, but it does make this unsightly blob on the entrance path.
![unsightly blob](https://cloud.githubusercontent.com/assets/7439907/8393313/b67c668a-1cd8-11e5-8f68-38ff52d55e1c.JPG)

**Comment by Gymnasiast** [comment]
This might take a few more decompilations to fully solve.

**Comment by Phasedetect** [comment]
This is fixed! But behavior is extraordinary. I'll upload a save so that you can try it, but the gist is: when you replace paths, they don't always connect. I was working in the save pictured above, and the paths refused to connect outside the park unless I either

* _dragged_ the path instead of clicking the actual spaces, or
* deleted all the hedges on the sides of the path

One pass with the clear scenery tool, and the path behaved correctly.

**Comment by Enzemo** [comment]
I've been affected by this bug again, so unfortunately it's not fixed. Oddly, my path is connected, and some guests will leave at random. They tend to get caught in a loop of walking around; I've constructed a path using no-entry signs to stop them turning at every corner, but even when forced to the exit, only about 1 in 50 will leave

**Comment by Gymnasiast** [comment]
Tested it with todays version. It now seems to be fixed.
