### ISSUE TITLE
Issues with objects not being found in latest Ubuntu build

### ISSUE THREAD

**Issue by Jademalo** [OpenRCT2/OpenRCT2#16589]
### Operating System

Ubuntu 20.04

### OpenRCT2 build

0.3.5.1-develop-0~3154-202202042302-gb5f649c97~ubuntu20.04.1

### Describe the issue

I'm running the latest Ubuntu build from the Launchpad Nightly builds.

I have a scenario with all official content enabled. I have also enabled the OpenRCT2 invisible station, paths, and void terrain. When trying to run it as a headless server, I get the following errors;
```
[official.terrain_edge.void] Object not found.
[openrct2.footpath_surface.queue_invisible] Object not found.
```
Manually copying those to the `/OpenRCT2/objects` folder seems to have fixed it, but I don't understand why the issue would be present in the first place. 

After checking `/usr/share/openrct2/object/official/`, `queue_invisible` is definitely not there, neither is `terrain_edge.void`.

### Area(s) with issue?

New Save Format (NSF), This bug is specific to multiplayer

### Steps to reproduce

1. Install on Ubuntu via the Launchpad Nightly builds
2. Create a scenario with all official content enabled, including `terrain_edge.void` and `queue_invisible`
3. Host a server with that scenario on the Ubuntu instance

**Comment by Gymnasiast** [comment]
I just pushed v1.2.6 of the objects to the special repo we use for Launchpad nightly builds. Should be fixed in the next build (which will be done overnight).

**Comment by Gymnasiast** [comment]
Have you been able to test today’s build?

**Comment by Jademalo** [comment]
Just tested `202202061717-g866ad2c01`, and it doesn't seem to have solved the issue. After uninstalling and reinstalling to make sure, those two files are still not included.

Though after poking through everything, I have a feeling it's just bad timings. Launchpad pulled at 12:14 UTC, Push to the GitHub repo was at 14:19 UTC, launchpad did the nightly build at 17:16 UTC, and then launchpad pulled at 18:14 UTC.

I'll check again after tomorrow's build, judging by the state of the launchpad repos it should all be in order after that.

**Comment by Jademalo** [comment]
Good news, following today's build everything seems to be working correctly!
