### ISSUE TITLE
Unable to set "same price throughout park" flag for on ride photos across different coaster types

### ISSUE THREAD

**Issue by CDB-Man** [OpenRCT2/OpenRCT2#17811]
### Operating System

Windows 10

### OpenRCT2 build

OpenRCT2, v0.4.1-185-g53f7a20 (53f7a20 on develop) provided by GitHub

### Describe the issue

If the "same price throughout park" flag for on ride photos on my Wooden Coaster is set, the same flag is disabled on all other coasters, and vice versa.

Also, if the price is changed on a ride with the flag = on, the price on rides with flag = off DOES change.
However, if the price is changed on a ride with flag = off, the price on rides with flag = on DOES NOT change.

![image](https://user-images.githubusercontent.com/14037303/184515842-49393c10-e571-4916-83d6-39b962b23fa5.png)

### Steps to reproduce

1. Download the attached save file
2. Open the price window for the 4 rides: Shuttle Loop, Mischief, Mini Corkscrew Circuit, Corkscrew Loop
3. Attempt to toggle the "same price throughout park" setting for on ride photos and observe behaviour
4. Attempt to change the photo price on rides with and without the flag set, and observe which rides do or do not change

### Attachments

[Mothball Mountain.zip](https://github.com/OpenRCT2/OpenRCT2/files/9332385/Mothball.Mountain.zip)

**Comment by Gymnasiast** [comment]
I believe this bug was very briefly in the game and has been fixed, could you check?

**Comment by CDB-Man** [comment]
> I believe this bug was very briefly in the game and has been fixed, could you check?

It looks like error bug persists in the reference file.  If I were to toggle the flag in any 1 of the rides, all 4 change.  Ie if I disable same price on Shuttle Loop, then both Corkscrews get disabled but Mischief gets enabled.

If the price is changed on whichever window has the flag turned ON, then all the other windows have their prices changed accordingly.  If the price is changed in a winder where the flag is turned OFF, then only that single window's price is changed.

====
However, when I create a new file and build a Wooden Coaster + Looping Coaster both with on ride photos, the behaviour there works as expected.

I'm guessing that go-forward behaviour works, but no "cleanup" or validation checks for existing save files that may have corrupt data?

**Comment by Gymnasiast** [comment]
I’ll investigate then. It shouldn’t be hard devising some sort of fix for this kind of situation.
