### ISSUE TITLE
Unable to play multiple RCT scenarios due to [rct1.footpath_surface.road] Object not found.

### ISSUE THREAD

**Issue by JimTacobs** [OpenRCT2/OpenRCT2#21166]
### Operating System

Ubuntu 22.04.3 LTS Linux (x86-64)

### OpenRCT2 build

OpenRCT2, v0.4.7 (, DEBUG)

### Base game

RollerCoaster Tycoon 2, RollerCoaster Tycoon Classic

### Area(s) with this issue?

This issue has to do with park objects and/or asset packs

### Describe the issue

When trying to load various scenarios (Bumbly Beach, Funtopia) that are part of the original RCT, I get hit with the following error. I've tried looking for this issue, but I seem to be the only one who has this?

[rct1.footpath_surface.road] Object not found.
Unable to open park: missing objects

I followed the Quick start guide on how to install on Ubuntu. I used the steam console. to download both depots for RCT Deluxe and RCT2.

When the error pops up, I get a `download all` button, but that doesn't do anything.

### Steps to reproduce

1. Clean install on Ubuntu, following your quick start guide, using steam -dev to download the depots from the console.
2. Add both RCT1 and RCT2 depots
3. Try and open Bumbly Beach / Funtopia.

**Comment by 733737** [comment]
try reinstalling

**Comment by Gymnasiast** [comment]
This is a packaging error in the PPA - the build string you posted suggest you’re using that.

We’ll look into it, in the meantime you could try the AppImage.

**Comment by Gymnasiast** [comment]
I pushed updated assets, which should hopefully find their way into the next nightly build (and next release build). Keeping this open until that build is done and the fix can be verified.

**Comment by JimTacobs** [comment]
Just updated and it wasn't resolved. Will try again tomorrow.

**Comment by Amyy** [comment]
For the issue still exists with 
- Dinky Park: `rct1.footpath_surface.road - unknown Object type` in `/Scenarios/sc8.sc4`
- Bumbly Beach: `rct1.footpath_surface.road - unknown Object type` in /Scenarios/SC5.SC4

I upgraded to this version of OpenRCT today:
`openrct2_0.4.8-develop-0~991-202402011453-gf2862861c~ubuntu22.04.1_amd64.deb`

**Comment by JimTacobs** [comment]
Works for me now. :)

**Comment by tupaschoal** [comment]
Nice, I'll close it as fixed then, thanks!
