### ISSUE TITLE
Game crashes when opening scenery window if no scenery is selected

### ISSUE THREAD

**Issue by fidwell** [OpenRCT2/OpenRCT2#24492]
### Operating System

Windows 11, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.22 (44aebeaf26 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This issue has to do with park objects and/or asset packs

### Describe the issue

Game crashes when opening scenery window if no scenery is selected

### Steps to reproduce

1. Open an empty workbench / sandbox park.
2. Go to cheats -> object selection.
3. Deselect all scenery groups and any stray scenery objects.
4. Close the object selection.
5. Click the scenery button in the toolbar.
6. Game crashes.
### Attachments

Crash dump files are zipped up here: [crash.zip](https://github.com/user-attachments/files/20427047/crash.zip)

**Comment by garrettleach** [comment]
This is probably fixed in the currently in development version v0.4.23 by #24371.

**Comment by fidwell** [comment]
I'm already on the latest develop version, so that either didn't fix it, or it's some other issue.

**Comment by 733737** [comment]
there's recently been changes to how the scenery window is formatted, if I'd have to venture the cause

**Comment by mixiate** [comment]
The commit in the issue is before the fix for divide by zero.
