### ISSUE TITLE
Duplicate of tracks

### ISSUE THREAD

**Issue by Aurorion** [OpenRCT2/OpenRCT2#24952]
### Operating System

Windows 11, Windows 10

### OpenRCT2 build

OpenRCT2, v0.4.25 (de986f58fd) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

When wanting to build a new ride the tracks show up 2 times per tracks (See attached screenshot).
I run a clean install of both RCT2 and OpenRCT2. RCT2 is installed under steam en OpenRCT2 under program files in my C drive.

When using the debug function it show that both entries point to the same file.
I tested this on a laptop and PC running windows 11 and a PC running windows 10. All with clean installs and all have tracks show up 2 times.

### Steps to reproduce

Have Windows 11.
Install RCT2 through steam.
Install OpenRCT2.
Try building a track and it should show duplicates in the list.

### Attachments

<img width="901" height="673" alt="Image" src="https://github.com/user-attachments/assets/b27e9ed0-039a-46ad-a33c-271484fcd703" />

**Comment by Lilithvia2** [comment]
Don't have this issue.

Try reinstalling?

**Comment by Aurorion** [comment]
I have tried that multiple times. No succes

**Comment by ZWx4** [comment]
I have the same issue on Bazzite (Fedora Linux) when launching RollerCoaster Tycoon 2: Triple Thrill Pack on Steam through OpenRCT2 v0.4.25 with the Luxtorpeda v73.0.1 compatibility tool for Steam.
Luxtorpeda seems to install OpenRCT2 into the same directory as `RCT2.EXE` is located in before running it. I think that could be part of the problem as this issue doesn't occur for me when launching OpenRCT2 via the official AppImage, even though the OpenRCT2 `readme.txt` file seems to imply that extracting OpenRCT2 to the RCT2 game directory is a supported installation method.

<img width="2560" height="1100" alt="Image" src="https://github.com/user-attachments/assets/abfa7748-8af9-4bc7-9f9d-e0949653aec4" />

I don't know why some of the OpenRCT2 files are dated 2019, but I can assure you it's v0.4.25.
<img width="500" height="100" alt="Image" src="https://github.com/user-attachments/assets/168a5141-7d0e-4b66-a2d0-a81c981c82a7" />

**Comment by Gymnasiast** [comment]
@Aurorion Should be fixed by https://github.com/OpenRCT2/OpenRCT2/pull/25561 . Could you try that out?

**Comment by RayKoopa** [comment]
I still have this issue in 0.5.1 - all prebuilts appear twice with the exact same path.

I have my RCT2 files copied to a portable location (the "assets" folder in the screenshot below), set in the options.

<img width="1281" height="695" alt="Image" src="https://github.com/user-attachments/assets/b93d3073-8ad6-4409-b9d0-3a516b208897" />

Is this related?

**Comment by 733737** [comment]
> I still have this issue in 0.5.1 - all prebuilts appear twice with the exact same path.
> 
> I have my RCT2 files copied to a portable location (the "assets" folder in the screenshot below), set in the options.
> <img alt="Image" width="1281" height="695" src="https://private-user-images.githubusercontent.com/9631152/600344652-b93d3073-8ad6-4409-b9d0-3a516b208897.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODAxOTQ3MDUsIm5iZiI6MTc4MDE5NDQwNSwicGF0aCI6Ii85NjMxMTUyLzYwMDM0NDY1Mi1iOTNkMzA3My04YWQ2LTQ0MDktYjlkMC0zYTUxNmIyMDg4OTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI2MDUzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNjA1MzFUMDIyNjQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTE4NDliNjBmYTE5ZWM2NzkzMzhlOWYwNTIyYzFkMDVmNWQyMTA0MjljNGI5MzZlNDkwNDE1ZmFiOTE4ODNiMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmcmVzcG9uc2UtY29udGVudC10eXBlPWltYWdlJTJGcG5nIn0.i3zUXCBgv0lJc5e4H7plLkqVgDvf1gj9pSO9pbL4Plw">
> 
> Is this related?

try deleting your tracks.idx file and rebuild your track index

**Comment by RayKoopa** [comment]
> try deleting your tracks.idx file and rebuild your track index

I tried that, deleted the tracks.idx, got a new one created, no change.
