### ISSUE TITLE
Segfault when trying to load WW/TT scenario when missing an object

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#2670]
To reproduce, try the following for example:
1. Move SCGMEDIV.DAT out of the ObjData folder.
2. Start OpenRCT2.
3. Attempt to load Medieval - Robin Hood.
4. OpenRCT2 segfaults.

**Comment by janisozaur** [comment]
That's already known, @IntelOrca should clean it up.

The crash happens in https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/rct2.c#L464 because https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/rct2.c#L239 is never called. Removing call to `longjmp` makes the game not crash, but report failure to load.

Requires some testing and checking.

**Comment by janisozaur** [comment]
Should be fixed with 3073bc64fddaf85634178aa594c6d732fb82485e can you check?

**Comment by Gymnasiast** [comment]
That doesn't fix it unfortunately.

**Comment by IntelOrca** [comment]
@janisozaur does it crash for you too?

**Comment by janisozaur** [comment]
Yes, it segfaults, though my park is named "Dark Age - Robin Hood", not "Medieval".

```
>>> bt
#0  0x0146719a in map_element_height (x=352, y=1440) at /home/janisozaur/workspace/OpenRCT2/src/world/map.c:386
#1  0x015052a0 in sub_689174 (x=0xffffd57e, y=0xffffd57c, z=0xffffd57a) at /home/janisozaur/workspace/OpenRCT2/src/interface/viewport.c:249
#2  0x015063c8 in viewport_update_position (window=0x1420078) at /home/janisozaur/workspace/OpenRCT2/src/interface/viewport.c:592
#3  0x0150ba93 in window_update_all_viewports () at /home/janisozaur/workspace/OpenRCT2/src/interface/window.c:162
#4  0x0150bad8 in window_update_all () at /home/janisozaur/workspace/OpenRCT2/src/interface/window.c:178
#5  0x0144fccd in rct2_draw () at /home/janisozaur/workspace/OpenRCT2/src/rct2.c:273
#6  0x01528d68 in openrct2_loop () at /home/janisozaur/workspace/OpenRCT2/src/openrct2.c:439
#7  0x015287c8 in openrct2_launch () at /home/janisozaur/workspace/OpenRCT2/src/openrct2.c:305
#8  0x01525adc in main (argc=1, argv=0xffffd724) at /home/janisozaur/workspace/OpenRCT2/src/platform/posix.c:57
>>> p mapElement
$1 = (rct_map_element *) 0x0
```

**Comment by IntelOrca** [comment]
Yeah, its "Dark Age - Robin Hood", not "Medieval".
I have fixed it now.

**Comment by octaroot** [comment]
This is still a problem in multiplayer, I believe. My game has RCT2 objects only, no expansions - trying to connect to a multiplayer game causes a segfault.

I'm running my own build (commit  083ec35362f4d16c2bb816bc7f2538f67532ad5f) on Linux, but this also happens when running a Windows build under Wine.

```
$ ./openrct2 
WARNING[/tmp/openrct2/OpenRCT2/src/rct2.c:567 (get_system_info)]: Function get_system_info at /tmp/openrct2/OpenRCT2/src/rct2.c:567 is a stub.

WARNING[/tmp/openrct2/OpenRCT2/src/platform/shared.c:935 (platform_load_cursors)]: Function platform_load_cursors at /tmp/openrct2/OpenRCT2/src/platform/shared.c:935 is a stub.

WARNING[/tmp/openrct2/OpenRCT2/src/network/network.cpp:1695 (Client_Handle_MAP)]: Received zlib-compressed sv6 map
ERROR[/tmp/openrct2/OpenRCT2/src/object.c:171 (object_load_chunk)]: object not installed
ERROR[/tmp/openrct2/OpenRCT2/src/object_list.c:562 (object_read_and_load_entries)]: failed to load entry: CROCFLUM
ERROR[/tmp/openrct2/OpenRCT2/src/object.c:171 (object_load_chunk)]: object not installed
ERROR[/tmp/openrct2/OpenRCT2/src/object_list.c:562 (object_read_and_load_entries)]: failed to load entry: DIAMONDR
 < a couple more of these, you get the idea >
ERROR[/tmp/openrct2/OpenRCT2/src/object.c:171 (object_load_chunk)]: object not installed
ERROR[/tmp/openrct2/OpenRCT2/src/object_list.c:562 (object_read_and_load_entries)]: failed to load entry: MEDIPATH
Segmentation fault
```
