### ISSUE TITLE
Text drawn outside window bounds causes glitches

### ISSUE THREAD

**Issue by marijnvdwerf** [OpenRCT2/OpenRCT2#2756]
![image](https://cloud.githubusercontent.com/assets/737603/12380127/04fe5aba-bd6b-11e5-8291-b387031ffa53.png)

To reproduce, set the in-game language to Dutch and open the options window. When dragging the leftover text outside window bounds breaks.

**Comment by marijnvdwerf** [comment]
This can also happen in the news feed. 
![image](https://cloud.githubusercontent.com/assets/737603/12380157/39b9845e-bd6c-11e5-8e14-8cb7bcfa53c0.png)

**Comment by sjoerddebruin** [comment]
Jup, reported some long translations in the past. Would be great if some interface elements were some more responsive or just wider by default. Dutch is not the only language where people use more words to describe the same thing. Not sure what to do with the newsfeed.

**Comment by mrtnptrs** [comment]
Just a general issue of all projects: buttons are sometimes too small for some translations. For Dutch this problem has been solved everywhere in the game. So, this isn't a real issue, because some buttons and windows should be larger or the translator could try to shorten the translation.

**Comment by tupaschoal** [comment]
Still happens on v0.3.1 with Deutsch and other languages, specially on the experimental lighting effects on rides
![image](https://user-images.githubusercontent.com/6443427/95152451-7457cd00-0763-11eb-9ee3-1a08f3dc6d14.png)

**Comment by AaronVanGeffen** [comment]
These should all be using clipped string drawing. I'm particularly surprised about the checkbox widgets, as they should be using this automatically/inherently.
