### ISSUE TITLE
Closing load system dialog window on OS X crashes the game

### ISSUE THREAD

**Issue by rvgr** [OpenRCT2/OpenRCT2#3242]
**OS:** Mac OS 10.11.4
**Version:** 0.0.4
**Commit:** c5ff5a3

When closing a load system dialog window on OS X (be it by clicking cancel or by loading a game), the game crashes:
- In windowed mode, the whole window freezes after the system dialog window disappears
- In fullscreen, the whole window goes black
- In fullscreen (borderless), the whole window freezes, the system dialog window flickers

In any case, you can hear the sounds of the loaded park, you can even interact with it (hearing sounds of new windows opening), but you can't see it as the window is freezed at the previous screen.

It only happens when loading a game, saving a game works fine.

Here's what pops in the system console when using system dialog window, don't know if it's helpful:

```
04/04/2016 10:32:04,517 sharedfilelistd[46931]: SecTaskLoadEntitlements failed error=22
04/04/2016 10:32:04,577 tccd[330]: SecTaskLoadEntitlements failed error=22
04/04/2016 10:32:04,581 tccd[330]: SecTaskLoadEntitlements failed error=22
04/04/2016 10:32:04,587 tccd[330]: SecTaskLoadEntitlements failed error=22
04/04/2016 10:32:04,589 WindowServer[46883]: SecTaskLoadEntitlements failed error=22
04/04/2016 10:32:04,589 tccd[384]: SecTaskLoadEntitlements failed error=22
04/04/2016 10:32:04,607 OpenRCT2[47197]: BUG in libdispatch client: kevent[EVFILT_MEMORYSTATUS] add: "Operation not supported" - 0x2d
04/04/2016 10:32:04,621 OpenRCT2[47197]: GetDYLDEntryPointWithImage(/System/Library/PrivateFrameworks/CacheDelete.framework/CacheDelete,CacheDeleteCopyPurgeableSpaceWithInfo) failed.
```

**Comment by YJSoft** [comment]
I think it's OSX's problem, not OpenRCT2 problem since there are similar issue at other project like atom.(https://github.com/atom/atom/issues/7811 https://github.com/atom/electron/issues/2178)

**Comment by rvgr** [comment]
This is strange, as I remember it working like two weeks ago, but I don't remember exactly when it stopped working.

**Comment by Gymnasiast** [comment]
Should have been fixed by https://github.com/OpenRCT2/OpenRCT2/commit/c5ff5a3ce908f137cc8f0d977ae4ccbcb29d5fd5 .

**Comment by rvgr** [comment]
I does not, https://github.com/OpenRCT2/OpenRCT2/commit/c5ff5a3ce908f137cc8f0d977ae4ccbcb29d5fd5 fixed #3234. This bug still exists in the last build.

**Comment by marijnvdwerf** [comment]
Definitely doesn't occur in the last build.

**Comment by rvgr** [comment]
It still occurs to me... Any idea on how to pinpoint what's causing it? I tried playing with several settings, but it keeps on happening.

Is the title sequence supposed to freeze when the dialog is open? Also there's a little lag before the window opens.

**Comment by janisozaur** [comment]
@rvgr run it in a debugger.

**Comment by rvgr** [comment]
@janisozaur I would like to, but I have basically zero developing knowledge and have no idea of how to do it...

**Comment by marijnvdwerf** [comment]
Just to be sure. What build version are you running?

**Comment by rvgr** [comment]
I'm running https://github.com/OpenRCT2/OpenRCT2/commit/1237bcab264402dc69e95d03a9b1d3074798ba79

**Comment by AaronVanGeffen** [comment]
Does this still happen? I cannot reproduce it.
