### ISSUE TITLE
Assertion Failed - Line 2934

### ISSUE THREAD

**Issue by Richard-L** [OpenRCT2/OpenRCT2#3326]
![image](https://cloud.githubusercontent.com/assets/4934209/14584183/138d7c4e-043a-11e6-9de3-f98e708d1d12.png)

Since new v004 I'm getting this on a lot of parks downloaded from NEDesigns.

**Comment by fromthere** [comment]
I need

- OS
- Version
- Commit(hash at main screen like e5666f2)
- Save game causing crash

to repruduce this issue.

**Comment by Richard-L** [comment]
Win10-x64
e5666f2

http://www.nedesigns.com/park/3404/paradise-pier/
http://www.nedesigns.com/park/3292/sunset-vista/
http://www.nedesigns.com/park/3411/h2h7-finals-manual-laborers-disneypunk/

^... all have the same problem. Occurs ~2mins of viewing the parks.

**Comment by fromthere** [comment]
`src/inteface/viewpoint.c`
```cpp
static bool sub_679074(rct_drawpixelinfo *dpi, int imageId, sint16 x, sint16 y) {
	sint16 before_x = RCT2_GLOBAL(0x9ABDAE, sint16);
	uint8 before_output = RCT2_GLOBAL(0x00141F569, uint8);

	RCT2_CALLPROC_X(0x00679074, 0, imageId, x, y, 0, (int) dpi, 0);
	sint16 original_x = RCT2_GLOBAL(0x9ABDAE, sint16);
	uint8 original_output = RCT2_GLOBAL(0x00141F569, uint8);

	RCT2_GLOBAL(0x9ABDAE, sint16) = before_x;
	RCT2_GLOBAL(0x00141F569, uint8) = before_output;

	bool new_output = new_sub_679074(dpi, imageId, x, y);
	sint16 new_x = RCT2_GLOBAL(0x9ABDAE, sint16);

	assert(new_x == original_x);
	assert(new_output == original_output);

	return new_output;
}
```
`new_sub_679074` returned `false` but original_output was `\x01`.

**Comment by duncanspumpkin** [comment]
This code is used to work out what your mouse is hovering over. If you can work out if it only happens at certain zooms that would be great

**Comment by Richard-L** [comment]
I'm fairly certain it only happened when all zoomed in.

**Comment by IntelOrca** [comment]
@Richard-L Yes we have just merged in our implementation for hit testing (what object is under the cursor).

The assertion is saying that our implementation isn't giving the same result as the original game.

**Comment by Richard-L** [comment]
c3ba519 still having this problem.

How can I downgrade to stable? ORCT2 has become unuable like this :(

**Comment by Richard-L** [comment]
![image](https://cloud.githubusercontent.com/assets/4934209/14589714/2dce67f8-04e9-11e6-896b-7d76065ff798.png)

How come I can't choose "stable" ?

On win10 as I said, so I tried to run the launcher "as administrator". Didn't help though.

**Comment by IntelOrca** [comment]
@Richard-L just download the stable portable zip or installer from openrct2.org

**Comment by Richard-L** [comment]
Thanks. With the launcher v005 I can now choose stable.

In dev, the error remains, just with a new line info now:

![image](https://cloud.githubusercontent.com/assets/4934209/14619072/f8d782aa-05b5-11e6-98a1-1eadc99f8ae6.png)

**Comment by duncanspumpkin** [comment]
Should be fixed now.
