### ISSUE TITLE
Singleplayer Crash

### ISSUE THREAD

**Issue by iliketousetransmissionformytorrents** [OpenRCT2/OpenRCT2#3790]
**OS:** 
Windows 8.1

**Version:** 
OpenRCT2 Build: 853

It's just a crash to desktop after about 5 seconds of being in this park. It's a collaboration park but not in multiplayer.

**Steps to reproduce:**
1. Open the park in OpenRCT2
2. Wait

**Dump file**
[OpenRCT2.zip](https://github.com/OpenRCT2/OpenRCT2/files/292237/OpenRCT2.zip)

**Save game:**
[Spayculowse Asylum 9.zip](https://github.com/OpenRCT2/OpenRCT2/files/292239/Spayculowse.Asylum.9.zip)

**Comment by iliketousetransmissionformytorrents** [comment]
So since some changes were commited, does that mean it will be in the next update?

**Comment by Patrik356b** [comment]
Probably.

**Comment by iliketousetransmissionformytorrents** [comment]
I don't really what it looks liek when updates get pushed through with the Launcher, but I saw a loading animation appear and tried out the park again. It still crashes with the same error.

**Comment by Nubbie** [comment]
This isn't in-game yet, it's still an open PR and hasn't been merged, you can find it here:
#3791 

When this gets merged, it should be fixed

**Comment by iliketousetransmissionformytorrents** [comment]
Ah, great, thank you Nubbie.

**Comment by Nubbie** [comment]
@iliketousetransmissionformytorrents 
This is now fixed, download the newest version and try to load the map!

**Comment by iliketousetransmissionformytorrents** [comment]
Still crashes for me!

OpenRCT2 Build: 928

[OpenRCT2.zip](https://github.com/OpenRCT2/OpenRCT2/files/321715/OpenRCT2.zip)

**Comment by janisozaur** [comment]
@iliketousetransmissionformytorrents the numbers you provide bear no meaning. Can you provide proper commits instead?

**Comment by Nubbie** [comment]
@iliketousetransmissionformytorrents 
Think you're saying the launchers numbers, could you provide the commit of the game?

You can find it in-game in the left bottom corner
![sghdfgsdfhdgs](https://cloud.githubusercontent.com/assets/17282384/16171377/c0e7bfb2-356d-11e6-854c-814d0f9f3d6e.png)
