### ISSUE TITLE
Multiplayer Crash on join,

### ISSUE THREAD

**Issue by Juli199696** [OpenRCT2/OpenRCT2#3811]
**OS: Windows 7 64Bit** 
**Version:0.0.5** 
**Commit:628e263** 

Explanation of the issue...
The client cant download the map or crash on a LINUX Server. Does not care if its Gui or Headless mode. Also its happening for other people too. 

Things so far testet that dont work. 

1. Run new config,
2. Always newest dev build.
3. Run the game with Wine and a windows exe dont work aswell. Client on windows crash. 

**Some Gitter Chatlog** from @janisozaur. Could be helpfull?

Server was handing out some malformed packets… or at least client interpreted them as such
 PACKET: 13, size: 54
PACKET: 1, size: 65012
PACKET: 1, size: 65012
PACKET: 968114734, size: 50272
PACKET: 457641970, size: 31584

Chat from @Juli199696
This was the last working https://transfer.sh/eUsYB/openrct2-linux.tar.gz where @janisozaur fixed something in the netcode
And the last server version i can get to work is the OpenRCT2-0.0.5.0-develop-91b7db3 commit
before the crash problem was there, as the current dont crash but cant download the map file

Whats working.
1. Connecting the Server and Client localy on the same machine.

**Dump file**
If you have a dump file, zip it and drag&drop it here.

https://www.dropbox.com/s/l8yie8wgxkg3gfk/b0f06e02-2b0b-4004-9108-f3aa5f3a9e54%28628e263%29.zip?dl=0
For some reason Github dont let me upload the zip file...

**Save game:**
[b0f06e02-2b0b-4004-9108-f3aa5f3a9e54.txt](https://github.com/OpenRCT2/OpenRCT2/files/297698/b0f06e02-2b0b-4004-9108-f3aa5f3a9e54.txt)

**Comment by Juli199696** [comment]
[Uploading b0f06e02-2b0b-4004-9108-f3aa5f3a9e54(628e263).zip…]()

**Comment by dVoCex** [comment]
Same problem,

**OS: Windows 10 64Bit 
Version: 0.0.5 
Commit: 428724d (client and server)**

**Dump file:**
[c15fe309-86c2-46d7-ade5-3924684b5821(428724d).zip](https://github.com/OpenRCT2/OpenRCT2/files/298133/c15fe309-86c2-46d7-ade5-3924684b5821.428724d.zip)

**Save game:**
[c15fe309-86c2-46d7-ade5-3924684b5821.zip](https://github.com/OpenRCT2/OpenRCT2/files/298134/c15fe309-86c2-46d7-ade5-3924684b5821.zip)

**Comment by janisozaur** [comment]
We've inspected information you provided, but cannot reproduce it locally. Can you describe exactly how you host, if there are any actions taken on a server, how does a client join? Every click, every option may count.

Can you provide the parks you're using for hosting (not the dumped ones)?

**Comment by Gymnasiast** [comment]
Reopening this as it's not yet solved according to the OP.

**Comment by janisozaur** [comment]
Please do not hijack issues. This was originally about (just like the title says) "Multiplayer crash on join" and we fixed that.

I am aware of server not being able to hand out maps properly from Linux, but this is something entirely different.

**Comment by Juli199696** [comment]
But my client still hangs up on that. Try to join "Freebuild, Autosave, Autorestart" and you will see it hangs up.

**Comment by dVoCex** [comment]
![hangup](https://cloud.githubusercontent.com/assets/2843239/15874684/9e03e262-2d04-11e6-9db7-c4da1ab299d6.gif)

That happens to me also when I connect to @Juli199696's server.

Otherwise download hangs but i can close / interrupt the window. If I dont close it, it'll crash after several minutes.

**Comment by IntelOrca** [comment]
@dVoCex please post that to #3836 instead.
