### ISSUE TITLE
Linux Servers send malformed packets

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#3836]
**OS:** Linux (seems to affect most distributions)
**Version:** 0.0.5
**Commit:** 0a4fa02a3e3d19700c0cb5d9bdd57c249aee9c47

```
PACKET: 13, size: 54
PACKET: 1, size: 65012
PACKET: 1, size: 65012
PACKET: 968114734, size: 50272
PACKET: 457641970, size: 31584
```

This causes clients to hang when downloading the map, but they can cancel the operation.

**Comment by janisozaur** [comment]
Initially believed to be caused be either https://github.com/OpenRCT2/OpenRCT2/pull/3782 or https://github.com/OpenRCT2/OpenRCT2/pull/3782 but then confirmed to happen on 9b705c5a7e52b49a6ddbb4969fbe608d948e365e, though this might be just a coincidence.

**Comment by Juli199696** [comment]
https://cloud.githubusercontent.com/assets/2843239/15874684/9e03e262-2d04-11e6-9db7-c4da1ab299d6.gif

**Comment by zsilencer** [comment]
i think this is because SendData is only returning bool and adding the total to the packet.transferred when it could be sending any number of bytes less than the tried amount.

**Comment by janisozaur** [comment]
This should potentially be fixed with https://github.com/OpenRCT2/OpenRCT2/pull/3844 can someone previously affected check that please?

**Comment by zsilencer** [comment]
That fixes another issue but the problem remains, send cant be guaranteed to send everything especially when nonblocking but it is being treated like it does.  The solution is to return how many bytes it actually sent and adding that to packet.transferred like it used to instead of the entire size of the buffer, so that it can try again later where it left off.

**Comment by janisozaur** [comment]
@zsilencer but with #3844 now, wouldn't it flush whole buffer to the wire and thus be treated as if it sends everything? See the loop it is wrapped in: https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/network/TcpSocket.cpp#L350-L360

Anyway, you're far more experienced with network than I am, if you know what should the fix be, could you make a PR?

**Comment by IntelOrca** [comment]
I think we need to do this anyway. If it blocks on sending the whole packet, it could cause the game to freeze if it takes to long - not to mention the rest of our stuff is multi-threaded and may time out.

**Comment by zsilencer** [comment]
OK I submitted a PR to your branch @janisozaur 

^ Yeah you don't want to create a loop that is converting a nonblocking call into a blocking one that uses 100% cpu (very horrible) but it is escaping out of it if it fails so it wont do that.

**Comment by michaelwang32** [comment]
This is what happens when I start my server. Everything appears normal on the server side.
![vlcsnap-2016-06-09-16h24m41s444](https://cloud.githubusercontent.com/assets/6281370/15945095/b1f32494-2e5e-11e6-9143-9b473e999568.png)
