### ISSUE TITLE
Crashes whenever I start OpenRCT2

### ISSUE THREAD

**Issue by Klocko** [OpenRCT2/OpenRCT2#3940]
**OS:** [e.g. Windows 8]
**Version:** [e.g. 0.0.5]
**Commit/Build:** [e.g. d892f6b]

Basically, I start OpenRCT2 and it crashes, simple as that. I have no idea why.
I have Rollercoaster Tycoon 2: Triple Thrill Pack, which I bought from Steam.

**Steps to reproduce:**
1. Steal my computer
2. Start OpenRCT2

**Dump file**
[e3fc5f75-0497-488f-b9ba-ecbaea09e9d9(d892f6b).zip](https://github.com/OpenRCT2/OpenRCT2/files/330068/e3fc5f75-0497-488f-b9ba-ecbaea09e9d9.d892f6b.zip)

**Comment by IntelOrca** [comment]
Try this version:
https://openrct2.org/downloads/develop/97fedab

**Comment by fivefuenf** [comment]
I've had the exact same problem, same error in the Dump-File.
The version you linked is working now.

**Comment by IntelOrca** [comment]
Can you now try the latest version and let me know if that works?

https://openrct2.org/downloads/develop/latest

**Comment by janisozaur** [comment]
should be fixed now

**Comment by Nubbie** [comment]
@Superjustinbros 
Could you run openrct2.exe from the command prompt and with --verbose as an argument?
This mean:

1.  Open a command prompt
2.  cd to the directory where openrct2.exe resides
3.  openrct2.exe --verbose


Can you then right click and copy all the text and paste it in here? (or at least show a screenshot at the end of the text)
_(copied from Dev Gymnasiast)_

**Comment by Nubbie** [comment]
```
>	openrct2.dll!object_type_large_scenery_load(void * objectEntry=0x0617f020, unsigned int entryIndex=0, int * chunkSize) Line 1561	C
 	openrct2.dll!object_load(int type=2, void * objectEntry=0x0617f020, unsigned int entryIndex=0, int * chunkSize=0x000cfb30) Line 2562	C
 	openrct2.dll!object_load_file(int groupIndex=-1, const rct_object_entry * entry, int * chunkSize=0x000cfb30, const rct_object_entry * installedObject=0x0161514b) Line 134	C
 	openrct2.dll!install_object_entry(rct_object_entry * entry=0x000cfb70, rct_object_entry * installed_entry=0x0161514b, const char * path, rct_object_filters * filter=0x000cfb54) Line 798	C
 	openrct2.dll!object_list_load(...) Line 349	C
 	openrct2.dll!rct2_init(...) Line 167	C
 	openrct2.dll!openrct2_initialise(...) Line 243	C
 	openrct2.dll!openrct2_launch(...) Line 271	C
 	openrct2.dll!StartOpenRCT(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance=0x00000000, char * lpCmdLine=0x015d4fd6, int nCmdShow=10) Line 109	C
 	openrct2.exe!004069e4()	Unknown
 	[Frames below may be incorrect and/or missing, no symbols loaded for openrct2.exe]	
 	[External Code]	
```

**Comment by janisozaur** [comment]
This is wake of #3897, which was fixed later on in https://github.com/OpenRCT2/OpenRCT2/commit/00bc8fadc484fb69362d29117ce6c7f41ad04c81 and reverted in #3951, no longer relevant.

**Comment by Superjustinbros** [comment]
Downloaded build 6a5ecf0 and it's still crashing.

[Crash July 6th.zip](https://github.com/OpenRCT2/OpenRCT2/files/351299/Crash.July.6th.zip)

I've heard that this was fixed at some point, so I'm not sure if one of the updates that I installed put in some kind of flag that bugs out every other version of the game I try to run.

**Comment by SijmenSchoon** [comment]
Have you tried deleting/moving the OpenRCT2 folder (%APPDATA%\OpenRCT2)?

**Comment by IntelOrca** [comment]
@SijmenSchoon we don't save the folder in AppData, we save it in Documents.

**Comment by SijmenSchoon** [comment]
Oh sorry, I'm not a Windows user. A quick Google turned up AppData, so that's why I said AppData
