### ISSUE TITLE
keep getting this crash dump. sorry if this is the wrong place for this

### ISSUE THREAD

**Issue by stefan084** [OpenRCT2/OpenRCT2#4546]
[Fill in the placeholders below. Delete any headings and placeholders that you do not fill in. Delete this line as well]

**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.0.5]
**Commit/Build:** [e.g. 426e106]

[Explanation of the issue...]

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. [step 1]
2. [step 2]

**Dump file**
[If you hav
[OPENRCTZIP.zip](https://github.com/OpenRCT2/OpenRCT2/files/514187/OPENRCTZIP.zip)
e a dump file: zip it before you drag & drop it here.]

**Screenshots / Video:**
[Drag & drop screenshots here. Use https://vid.me to upload video.]

**Save game:**
[Change the file extension to .txt or package to a .zip so that it can be drag & dropped here...]

**Comment by Nubbie** [comment]
It's not the wrong place for it

**Comment by janisozaur** [comment]
@stefan084 please fix description

**Comment by janisozaur** [comment]
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/3769

**Comment by stefan084** [comment]
why is this closed?

**Comment by duncanspumpkin** [comment]
Because it's a duplicate

**Comment by stefan084** [comment]
so someone has already had this problem and it was solved?

**Comment by duncanspumpkin** [comment]
No it's not solved but there is no need to have multiple issues for the same crash

**Comment by stefan084** [comment]
ok thanks. will I be notified if someone finds a solution?

**Comment by Nubbie** [comment]
@stefan084 You will be if you go to the other post #3769 and make a post, then you should get an e-mail every time something new happens :) 
[Make sure to check the watch setting so it's on watching](https://cloud.githubusercontent.com/assets/17282384/19216710/02045b1a-8dc8-11e6-8da5-c34c8658e517.png)
