### ISSUE TITLE
Custom Water not displaying correctly

### ISSUE THREAD

**Issue by RealRexen** [OpenRCT2/OpenRCT2#4605]
OS: Win10
Version 0.0.5
Build 6cb9297
This image here, http://i.imgur.com/wd9f1SX.png shows the water in the steam version of the game. This image is shows it in OpenRCT2 http://i.imgur.com/PBcIa5E.png Link to said object https://1drv.ms/u/s!AnIDdSY_cTSAvzBxiOLfz4dJfHGO for testing/debugging.
The odd thing is when the  object management window gets reopened the water then displays correctly.

**Comment by Nubbie** [comment]
Cowl avatar, but also, recommend zipping up the files to .zip/.rar and post them in here for easy access :+1:

**Comment by RealRexen** [comment]
Sorry this was a re-post from the subreddit .

**Comment by kingcailan** [comment]
Have you tried changing the renderer? If you're using OpenGL, it changes the way water renders. I've noticed this in the vanilla water, I haven't tried any custom water yet though. I'll try it when I ge home and update you then.

**Comment by RealRexen** [comment]
I use only software or software with hardware never OpenGL.

**Comment by autofire372** [comment]
This is still an issue, and occurs with the pink water DAT that Chris Sawyer released a while back.

**Comment by AaronVanGeffen** [comment]
Has this been resolved in the mean time?

**Comment by RealRexen** [comment]
Still broken 
![Forest Frontiers 2020-06-09 13-52-55](https://user-images.githubusercontent.com/18408903/84182745-dffd8800-aa58-11ea-9513-853b6cd1000d.png)

**Comment by AaronVanGeffen** [comment]
The object linked on OneDrive in the original post has since expired. Could you attach it here? (GitHub will accept it if you zip it first.)

**Comment by RealRexen** [comment]
Here you go
[rexen_s_water_pack.zip](https://github.com/OpenRCT2/OpenRCT2/files/4754008/rexen_s_water_pack.zip)

**Comment by Gymnasiast** [comment]
Do I understand correctly that it gets glitchy after you changed the water type?
