### ISSUE TITLE
Mini golf window shows more players than there actually are

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#474]
Another bug with the ride window is the number of vehicles in the paint tab and also the number of players you can focus the viewport on in the main tab for golf.

**Comment by mrtnptrs** [comment]
Aren't the above bugs fixed now we use our own window drawing code?

**Comment by rwjuk** [comment]
Cannot reproduce - I imagine this was fixed when we moved away from hooking into the original EXE.

**Comment by Gymnasiast** [comment]
I believe the Mini golf window still shows more people than are on the course.

**Comment by deurklink** [comment]
Oof. Wanted to paint my ride which has 40 vehicles. I guess this belongs here rather than in a separate issue.

![image](https://user-images.githubusercontent.com/6469413/39064463-e7317e3e-44ce-11e8-973d-baafc7b58736.png)

**Comment by Gymnasiast** [comment]
It belongs in a separate issue.

**Comment by Gymnasiast** [comment]
The solution would be to add a flag to the vehicle, .e.g. `isInvisible`. This could then also be used on stuff like Amazing Earl’s "body slide" and "swim ride".
