### ISSUE TITLE
White/Ghost objects when near object limit

### ISSUE THREAD

**Issue by thiebert** [OpenRCT2/OpenRCT2#6259]
**OS:** Windows 7
**Version:** 0.1.2
**Commit/Build:**  0fe1814

Parks at/near the object limit produce ghost objects if scenery is dragged around, even without it being placed. These ghost objects take up object slots, which are obviously super valuable in parks near the limit.

- [ X ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Open this park (Or any other at the object limit): https://www.nedesigns.com/park/1490/legacies-themepark-europe/
2. Delete some objects to free up some slots
3. Drag an object around in places where it can be built.
4. Ghost objects appear.

**Comment by Gymnasiast** [comment]
Cannot reproduce in 8bab0c747934f5254fc78b7f75e40c480a959d97 , assuming it has been fixed.

**Comment by thiebert** [comment]
https://www.youtube.com/watch?v=n7Fv7xgmHFw&feature=youtu.be

on `efada44`

**Comment by thiebert** [comment]
Sorry I don't have the file to share, but it is still occurring.

**Comment by thiebert** [comment]
@Gymnasiast 
I'm able to reproduce this, but only with objects that are larger than one tile. Import the sphinx into the park linked above, and the issue should present itself.
