### ISSUE TITLE
Screen continues to scroll in windowed mode after the mouse leaves the window

### ISSUE THREAD

**Issue by RollingStar** [OpenRCT2/OpenRCT2#695]
When the mouse is next to a screen edge the screen scrolls as normal. But when the mouse is moved off the window, the screen continues to scroll until it reaches the edge of the map.

The way RCT1 (windowed) handles this is by never scrolling when at window edge (even when this option is enabled). I don't recall how RCT2 (windowed hack by Toadking) handles it.

I like the scrolling when at screen edge; I just wish there was a way to leave the window without scrolling forever. (Alt-tab to leave the window does work.) I know ORCT2 is not the only program that struggles with this. Maybe I'm asking for something that's not possible in a Windows program.

**Comment by IntelOrca** [comment]
I know how I would fix this for Windows using various windows API functions, but I don't know of a cross platform way or whether SDL2 has anything that would be useful.

**Comment by vzybilly** [comment]
I'm not sure about cross-platform/SDL but from my Java knowledge, this is also a fair issue for almost all programs that allow scrolling. I think a simple way would be a "scroll check" that is "window is active" along with "Mouse in window" if both are true then scroll.

I believe there are two ways to get where the mouse is for a game window, have the language tell you when the mouse moves and to poll where the mouse is on the window. I think polling is more common for scrolling features. scrolling while outside window bounds can be fixed by having a "no scroll" border along the game window, about five pixels or so. but the issue with that is if the mouse moves quickly. the example is if you're 10 pixels from the edge and the no scroll is 5 pixels from the edge, if you move 20 pixels past the edge and outside the game window, the window will tell the "last window position" which would still be the same even though the mouse is moving outside the window, the game will think it has just stopped in the scrolling zone of it's window.

I get around these issues by hacking that, I almost slam my mouse to the side, making it still be to far in the game to scroll but I'm actually using it outside the game, the only issue is going back over the game window while it's visible but not needing to be the current active window... I'll check if SDL2 can do mouse checks and window checks... I think the simple algorithm would be something more like:

location = Screen.Mouse.location - Screen.Window.location
if (either x or y is negetive) or (either x or y is greater than the size of the window), mouse is outside window.
if mouse is inside window, is our window active or ontop?
if so, scroll.

**Comment by RollingStar** [comment]
Since alt-tab already works, what if alt or another key could be used to override the screen scrolling (as a temporary measure)? When alt is held and mouse is at screen border, don't move screen. When alt is lifted, do not scroll screen until the mouse meets *another* screen border.

**Comment by IntelOrca** [comment]
Its not necessarily, we can easily use Windows' **GetCursorPos**, **GetClientRect** and **ClientToScreen** to determine whether the cursor is within the window or not.

I was just wondering if SDL2 maybe had an event for the cursor leaving the window or something for a more cross platform solution.

**Comment by adrian17** [comment]
[SDL_WINDOWEVENT_LEAVE](https://wiki.libsdl.org/SDL_WindowEventID)?

**Comment by webhawk** [comment]
Just an idea here, if you can capture the mouse location on the screen, you could make it that it keeps on scrolling when the mouse leaves the window by only a few (32?) pixels. This makes edge scrolling in windowed mode a bit more comfortable. When you leave the window by more then 32 pixels it would stop scrolling. 

This way you can even make it possible to scroll without the window having focus. (But, this would only be useful if the window is not covered by another window).

**Comment by janisozaur** [comment]
Isn't it fixed now?

**Comment by Nubbie** [comment]
@janisozaur 
It's not fixed, it acts a bit weird too
It only stops scrolling against the right side
Up, left & down is the same (See video)


https://vid.me/2Jl1

**Comment by Patrik356b** [comment]
@webhawk it would make odd behaviour when I record things using ScreenToGIF as it has a frame with buttons that I normally keep just outside of the game window. 

https://screentogif.codeplex.com

**Comment by PureTryOut** [comment]
Nowadays the screen only scrolls in windowed mode if the mouse is outside of the window, which seems like the preferable option for me. Alt+tabbing and moving the mouse away doesn't make the screen scroll which also seems like the preferable behaviour. I guess this issue can be closed?

**Comment by tupaschoal** [comment]
I agree with PureTryOut, so I'm closing the issue
