### ISSUE TITLE
Scenery items disappear from tab when loading save file.

### ISSUE THREAD

**Issue by deurklink** [OpenRCT2/OpenRCT2#6995]
**OS:** Windows 8.1
**Version:** 0.1.1
**Commit/Build:** 9f8e324 - Not sure which build was first to cause this, sadly have no time to check them all now..

When I load this save game and go to the scenery tab, I only see the tabs for gardens and a question mark tab, in weird locations. When I press the question mark, all scenery items disappear. Problem fixes itself when I go to object selection menu.
EDIT: It looks like it is something specific in this save file, the previous versions act normally. Also attached a previous version, for comparison.

**Steps to reproduce:**
1. Load attached save game
2. Go to scenery tab

**Screenshots / Video:**
![space base 2018-01-10 23-36-03](https://user-images.githubusercontent.com/6469413/34799708-1a2c2c92-f661-11e7-897b-2f4b7bf3d702.png)

**Save game:**
[Space Base 14.zip](https://github.com/OpenRCT2/OpenRCT2/files/1620673/Space.Base.14.zip)
Save game without problems:
[Space Base 13.zip](https://github.com/OpenRCT2/OpenRCT2/files/1620681/Space.Base.13.zip)

**Comment by rwjuk** [comment]
This should've been fixed in the latest commit (https://github.com/OpenRCT2/OpenRCT2/commit/ce9a72a4e9d57b192af7e714f99600f88782ea9b) - could you retry with the latest build?

**Comment by deurklink** [comment]
Loading the save game with the newest build didn't fix the problem by itself. 
Going to object selection to properly reload scenery again, and then saving the game once again in the latest commit seems to have fixed the problem!

**Comment by rwjuk** [comment]
Hmm... this still needs looking into if the problem reoccurs on each load however - are other save games broken?

**Comment by deurklink** [comment]
No other save games of mine are broken, it was just this specific one.

**Comment by rwjuk** [comment]
Ahh, gotcha. Looks like case closed then! :)

**Comment by Gymnasiast** [comment]
Games saved between the offending commit and the fix are all broken. Opening and closing object selection, then saving solves the issue.
